In [1]:
import pandas as pd     #pandas helps in reading the file and converting it into dataframe
import numpy as np      #numpy helps in converting dataframe into numpy arrays

In [2]:
train=pd.read_csv("F:\MACHINE LEARNING\Project/finance_train_data.csv")  #reading the given csv file

In [3]:
train.head()      #it will display top 5 elements of the file

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
train.tail()       #it will display bottom five elements of the file

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [5]:
train.describe()        #it will return statsitical analysis of the dataframe

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [6]:
train.dtypes          #it will return datatype of each column

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [7]:
train.info()       #it will return number of columns, total number of elements, column names, datatype of each column and number of non-null count of individual columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [8]:
train.columns     #it will return column names.

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [9]:
train["Loan_Status"].value_counts()      

Y    422
N    192
Name: Loan_Status, dtype: int64

In [10]:
# Using the below piece of code we are checking how many null(NaN) elements are present in each row.
category=["Gender","Married",'Dependents','Loan_Amount_Term','Credit_History','Self_Employed','LoanAmount']
for i in category:
    print(train[i].isnull().value_counts())

False    601
True      13
Name: Gender, dtype: int64
False    611
True       3
Name: Married, dtype: int64
False    599
True      15
Name: Dependents, dtype: int64
False    600
True      14
Name: Loan_Amount_Term, dtype: int64
False    564
True      50
Name: Credit_History, dtype: int64
False    582
True      32
Name: Self_Employed, dtype: int64
False    592
True      22
Name: LoanAmount, dtype: int64


In [11]:
# using the below piece of code we are filling the NaN with mode,mean.
train['Gender'].fillna(train['Gender'].mode()[0], inplace=True)     #mode-the element which occurs many times.
train['Married'].fillna(train['Married'].mode()[0], inplace=True)
train['Dependents'].fillna(train['Dependents'].mode()[0], inplace=True)
train['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0], inplace=True)
train['Credit_History'].fillna(train['Credit_History'].mode()[0], inplace=True)
train['Self_Employed'].fillna(train['Self_Employed'].mode()[0], inplace=True)
train['LoanAmount'].fillna(train['LoanAmount'].mean(), inplace=True)  #mean-the average of all elements 

In [12]:
#Using this small piece of code we are converting non-integer values into integers.
from sklearn.preprocessing import LabelEncoder
category= ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status'] 
encoder= LabelEncoder()
for i in category:   
    train[i] = encoder.fit_transform(train[i]) 
train.dtypes

Loan_ID               object
Gender                 int32
Married                int32
Dependents             int32
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
Loan_Status            int32
dtype: object

In [13]:
train.corr()          #corr() method will return how one variable is dependent with other one. A number closer to 1 means highly correlated/dependent and vice-versa. 

Gender   Married  Dependents  Education  Self_Employed  \
Gender             1.000000  0.364569    0.172914   0.045364      -0.000525   
Married            0.364569  1.000000    0.334216   0.012304       0.004489   
Dependents         0.172914  0.334216    1.000000   0.055752       0.056798   
Education          0.045364  0.012304    0.055752   1.000000      -0.010383   
Self_Employed     -0.000525  0.004489    0.056798  -0.010383       1.000000   
ApplicantIncome    0.058809  0.051708    0.118202  -0.140760       0.127180   
CoapplicantIncome  0.082912  0.075948    0.030430  -0.062290      -0.016100   
LoanAmount         0.107930  0.147141    0.163106  -0.166998       0.115260   
Loan_Amount_Term  -0.074030 -0.100912   -0.103864  -0.073928      -0.033739   
Credit_History     0.009170  0.010938   -0.040160  -0.073658      -0.001550   
Property_Area     -0.025752  0.004257   -0.000244  -0.065243      -0.030860   
Loan_Status        0.017987  0.091478    0.010118  -0.085884      -0.003700   

                   ApplicantIncome  CoapplicantIncome  LoanAmount  \
Gender                    0.058809           0.082912    0.107930   
Married                   0.051708           0.075948    0.147141   
Dependents                0.118202           0.030430    0.163106   
Education                -0.140760          -0.062290   -0.166998   
Self_Employed             0.127180          -0.016100    0.115260   
ApplicantIncome           1.000000          -0.116605    0.565620   
CoapplicantIncome        -0.116605           1.000000    0.187828   
LoanAmount                0.565620           0.187828    1.000000   
Loan_Amount_Term         -0.046531          -0.059383    0.036475   
Credit_History           -0.018615           0.011134   -0.001431   
Property_Area            -0.009500           0.010522   -0.044776   
Loan_Status              -0.004710          -0.059187   -0.036416   

                   Loan_Amount_Term  Credit_History  Property_Area  \
Gender                    -0.074030        0.009170      -0.025752   
Married                   -0.100912        0.010938       0.004257   
Dependents                -0.103864       -0.040160      -0.000244   
Education                 -0.073928       -0.073658      -0.065243   
Self_Employed             -0.033739       -0.001550      -0.030860   
ApplicantIncome           -0.046531       -0.018615      -0.009500   
CoapplicantIncome         -0.059383        0.011134       0.010522   
LoanAmount                 0.036475       -0.001431      -0.044776   
Loan_Amount_Term           1.000000       -0.004705      -0.076120   
Credit_History            -0.004705        1.000000       0.001963   
Property_Area             -0.076120        0.001963       1.000000   
Loan_Status               -0.022549        0.540556       0.032112   

                   Loan_Status  
Gender                0.017987  
Married               0.091478  
Dependents            0.010118  
Education            -0.085884  
Self_Employed        -0.003700  
ApplicantIncome      -0.004710  
CoapplicantIncome    -0.059187  
LoanAmount           -0.036416  
Loan_Amount_Term     -0.022549  
Credit_History        0.540556  
Property_Area         0.032112  
Loan_Status           1.000000

To use scikit-learn library, we have to convert the Pandas data frame to a Numpy array

In [14]:
X=train[['Gender', 'Married', 'Dependents', 'Education','Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount','Loan_Amount_Term', 'Credit_History', 'Property_Area']].values
X[0:5]    #we are converting dataframe into numpy arrays.

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.84900000e+03, 0.00000000e+00, 1.46412162e+02,
        3.60000000e+02, 1.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.58300000e+03, 1.50800000e+03, 1.28000000e+02,
        3.60000000e+02, 1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 3.00000000e+03, 0.00000000e+00, 6.60000000e+01,
        3.60000000e+02, 1.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.58300000e+03, 2.35800000e+03, 1.20000000e+02,
        3.60000000e+02, 1.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 6.00000000e+03, 0.00000000e+00, 1.41000000e+02,
        3.60000000e+02, 1.00000000e+00, 2.00000000e+

In [15]:
Y=train["Loan_Status"].values      #we are converting dataframe into numpy arrays.
Y[0:5]

array([1, 0, 1, 1, 1])

Data Standardization give data zero mean and unit variance, it is good practice

In [16]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 0.47234264, -1.37208932, -0.73780632, -0.52836225, -0.39260074,
         0.07299082, -0.55448733,  0.        ,  0.2732313 ,  0.41173269,
         1.22329839],
       [ 0.47234264,  0.72881553,  0.25346957, -0.52836225, -0.39260074,
        -0.13441195, -0.03873155, -0.21927331,  0.2732313 ,  0.41173269,
        -1.31851281],
       [ 0.47234264,  0.72881553, -0.73780632, -0.52836225,  2.54711697,
        -0.39374734, -0.55448733, -0.957641  ,  0.2732313 ,  0.41173269,
         1.22329839],
       [ 0.47234264,  0.72881553, -0.73780632,  1.89264089, -0.39260074,
        -0.46206247,  0.2519796 , -0.31454656,  0.2732313 ,  0.41173269,
         1.22329839],
       [ 0.47234264, -1.37208932, -0.73780632, -0.52836225, -0.39260074,
         0.09772844, -0.55448733, -0.06445428,  0.2732313 ,  0.41173269,
         1.22329839]])

In [17]:
#we are splitting the train dataframe into train test.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (491, 11) (491,)
Test set: (123, 11) (123,)


# Logistic Regression model 

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)    #Building/Training the model.
LR

LogisticRegression(C=0.01, solver='liblinear')

In [19]:
yhat = LR.predict(X_test)          # making predictions based on the trained model.
yhat

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1])

In [20]:
yhat_prob = LR.predict_proba(X_test)     #it willreturn the probability of either being 0 or 1.
yhat_prob

array([[0.38304838, 0.61695162],
       [0.2946126 , 0.7053874 ],
       [0.3258082 , 0.6741918 ],
       [0.35644401, 0.64355599],
       [0.2922254 , 0.7077746 ],
       [0.43821269, 0.56178731],
       [0.32812823, 0.67187177],
       [0.66295258, 0.33704742],
       [0.37644789, 0.62355211],
       [0.45308083, 0.54691917],
       [0.36270198, 0.63729802],
       [0.3507957 , 0.6492043 ],
       [0.32319873, 0.67680127],
       [0.32706331, 0.67293669],
       [0.73080688, 0.26919312],
       [0.30090553, 0.69909447],
       [0.36245378, 0.63754622],
       [0.33174246, 0.66825754],
       [0.38590959, 0.61409041],
       [0.32820699, 0.67179301],
       [0.74873398, 0.25126602],
       [0.31620682, 0.68379318],
       [0.29346048, 0.70653952],
       [0.29312878, 0.70687122],
       [0.73594785, 0.26405215],
       [0.32774885, 0.67225115],
       [0.36872623, 0.63127377],
       [0.38007967, 0.61992033],
       [0.34688288, 0.65311712],
       [0.30015119, 0.69984881],
       [0.

In [21]:
import sklearn.metrics as metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
accuracy = metrics.accuracy_score(yhat,y_test)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))     #Accuracy of the model
print("r2_score:",r2_score(y_test, yhat))               #R2 value
print("mse:",mean_squared_error(y_test, yhat))          #MSE(Mean square Error) of the model

Accuracy : 79.675%
r2_score: 0.0737951807228916
mse: 0.2032520325203252


# KNN(K-th Nearest Neighbour Model)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import sklearn.metrics as metrics

In [40]:
#Finding the best value of K
Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.6504065 , 0.6097561 , 0.72357724, 0.72357724, 0.77235772,
       0.76422764, 0.78861789, 0.7804878 , 0.76422764])

In [24]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1)

The best accuracy was with 0.7886178861788617 with k= 7


In [25]:
k = 7
#Train Model  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)     #Model Training
neigh

KNeighborsClassifier(n_neighbors=7)

In [27]:
yhat = neigh.predict(X_test)                    #Predicting values by using trained model
yhat

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1])

In [28]:
import sklearn.metrics as metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
accuracy = metrics.accuracy_score(yhat,y_test)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))            #Accuracy of the model
print("r2_score:",r2_score(y_test, yhat))                      #R2 value
print("mse:",mean_squared_error(y_test, yhat))                 #MSE(Mean Square Error) of the model

Accuracy : 78.862%
r2_score: 0.0367469879518072
mse: 0.21138211382113822


# For the given test dataset we need to predict LoanStatus using given independent variables and need to update the csv file

In [29]:
df=pd.read_csv("F:\MACHINE LEARNING\Project/finance_test_data.csv")     #reading the test dataset for which we need to predict loanStatus.

In [30]:
#Data PreProcessing(Filling NaN with mean,mode)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)
df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)
df['LoanAmount'].fillna(df['LoanAmount'].mean(), inplace=True)

In [31]:
#converting non-integer datatypes into integers
from sklearn.preprocessing import LabelEncoder
category= ['Gender','Married','Dependents','Education','Self_Employed','Property_Area'] 
encoder= LabelEncoder()
for i in category:   
    df[i] = encoder.fit_transform(df[i]) 
df.dtypes

Loan_ID               object
Gender                 int32
Married                int32
Dependents             int32
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
dtype: object

In [32]:
#converting dataframe into numpy arrays
N=df[['Gender', 'Married', 'Dependents', 'Education','Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount','Loan_Amount_Term', 'Credit_History', 'Property_Area']].values

In [33]:
from sklearn import preprocessing
N = preprocessing.StandardScaler().fit(N).transform(N.astype(float))

In [34]:
yhat = neigh.predict(N)        #predicting values using KNN Model

In [35]:
print(yhat)

[1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1
 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0
 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]


In [36]:
df["Loan_Status"]=yhat

In [37]:
df.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001015       1        1           0          0              0   
1  LP001022       1        1           1          0              0   
2  LP001031       1        1           2          0              0   
3  LP001035       1        1           2          0              0   
4  LP001051       1        0           0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              2            1  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [38]:
df["Loan_Status"].replace({1:"Y",0:"N"},inplace=True)
df["Gender"].replace({1:"Male",0:"Female"},inplace=True)
df["Married"].replace({1:"Yes",0:"No"},inplace=True)
df["Education"].replace({1:"Not Graduate",0:"Graduate"},inplace=True)
df["Self_Employed"].replace({1:"Yes",0:"No"},inplace=True)
df["Property_Area"].replace({0:"Rural",1:"Semiurban",2:"Urban"},inplace=True)

In [46]:
df.to_csv("F:\MACHINE LEARNING\Project/Final_output.csv")